### ISSUE TITLE
Join Request functionality

### ISSUE THREAD

**Issue by podnesTaF** [podnesTaF/AceBattleEvents#66]
1. Create status alerts after user applied to join a club and when admin accept or decline user to join
2. Send email to runner if he joined or declined
3. Send email to manager if someone applied to join his club.
4. Manager can send request to join the club to the runner. The runner will get it on both email and account inbox.

**Comment by mustafaazad03** [comment]
Hi, 
I am interested in this issue, Can you tell me how to reproduce it?

**Comment by podnesTaF** [comment]
I'm writing issues as 

> 

I'm usually writing issues as next steps in development of my applications. So it's not an actual issue it's just a task
